# Generated by Django 3.1.1 on 2020-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201006_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='length',
            field=models.IntegerField(default=12),
        ),
    ]
