# Generated by Django 3.1.1 on 2020-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201006_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[('0', 'Cancelled'), ('1', 'Confirmed'), ('2', 'On Hold')]),
        ),
    ]
